config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/set_lv'
  get 'home/set_rus'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_lang

  def index
  end

  def set_lv
    session[:lang] = :lv
    redirect_to root_path
  end

  def set_rus
    session[:lang] = :rus
    redirect_to root_path
  end

  private

    def set_lang
      session[:lang] ||= :rus
      @language = session[:lang]
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_lv.html.slim
.details
  h2 Rekvizīti:
  dl
    dt Swedbank
    dd
      b Konts: LV52HABA0551038577436
      br
      b Ludmila Ivanova (pers.kods 300967-10223)
  p 
    | Jautājumi: 
    b
      = mail_to 'emergencyhelpforlina@gmail.com'
    
.text

  h3.text-center Lūgums palīdzēt!
  p
    br
    | Skolēni, vecāki, draugi, visi, kas neesat vienaldzīgi!
    br
    | 20.jūnijā autoavārijā pie veikala ,,Depo" smagi cietusi Lina Jakimoviča.
    br
    br
    | Brīdī, kad Lina no stāvvietā novietotās automašīnas bagāžas nodalījuma izņēma somu, viņai no mugurpuses uztriecās cita automašīna. Lina tika saspiesta starp abiem automobiļiem un guva ļoti smagas traumas - vaļējus kāju lūzumus un asinsvadu bojājumus. 21.jūnijā Lina ar helikopteru tika nogādāta Rīgā, taču diemžēl 
    b.red kāju saglabāt neizdevās, to nācās amputēt.
    br
    br
    | Lina ir garā stiprs cilvēks, sportiste, kas pieradusi cīnīties ar grūtībām, bet tagad viņai būs jāpārdzīvo sarežģīts adaptācijas periods, un tam būs vajadzīga mūsu palīdzība un atbalsts. Ārstēšanai un rehabilitācijai nepieciešami līdzekļi.
    br
    br
    | "AS Swedbank" ir atvērts ziedojumu konts, saņēmējs - Linas māte Ludmila Ivanova.
    br
    br
    | Viņas rekvizīti:
    br
    b.red LV52HABA0551038577436 , personas kods 300967-10223.
    br
    br
    

    h4 Papildus informācija:
    br
    = link_to 'http://grani.lv', 'http://www.grani.lv/daugavpils/45218-mama-u-menya-net-nogi.html', target: '_blank'
    br
    = link_to 'http://news2night.com', 'http://news2night.com/en/news/postradavshaja-v-avarii-devushka-vertoletom-dostavlena-v-rigu', target: '_blank'
    br
    = link_to 'http://www.tvnet.lv', 'http://rus.tvnet.lv/novosti/kriminal_i_chp/261490-tragichnoje_dtp_v_daugavpilsje_djevushka_ostalas_bjez_nogi?utm_source=www.tvnet.lv&utm_medium=self_ads&utm_campaign=Selfads_in_www.tvnet', target: '_blank'
    br
    = link_to 'http://www.nasha.lv', 'http://www.nasha.lv/rus/novosti/news/incident/150166.html', target: '_blank'

    br
    br
    iframe.video width="640" height="480" src="//www.youtube.com/embed/WnLxNy4k7Qs" frameborder="0" allowfullscreen 


    h3
      | Mūsu spēkos nav mainīt notikušo, bet mēs varam palīdzēt Linai atgriezties pilnvērtīgā dzīvē!

app/views/home/_rus.html.slim
.details
  h2 Реквизиты:
  dl
    dt Swedbank
    dd
      b Номер счета: LV52HABA0551038577436
      br
      b Ludmila Ivanova (pers.kods 300967-10223)
  p 
    | Вопросы: 
    b
      = mail_to 'emergencyhelpforlina@gmail.com'
.text

  h3.text-center Просьба о помощи!
  p
    br
    | Ученики, их родители, друзья, все неравнодушные люди!
    br
    br
    | 20 июня в результате автоаварии в районе магазина «Депо» пострадала 17-летняя Лина Якимович. Лина доставала из багажника сумку, когда в припаркованный автомобиль сзади врезалась другая машина. В результате Лина оказалась зажатой между двумя автомобилями и получила серьезные травмы – открытые переломы ног, повреждения кровеносных сосудов. 21 июня на вертолете Лину доставили в Ригу, но,
    b.red &nbsp к сожалению, ногу спасти не удалось, ее пришлось ампутировать.
    br
    br
    | Лина – сильный духом человек, спортсменка, которая привыкла бороться с трудностями, но сейчас ей придется пережить очень сложный период адаптации к новой жизни и потребуется наша помощь и поддержка. Для лечения и реабилитации необходимы средства.
    br
    br
    | На имя Лининой мамы в Swedbank был открыт счет, его реквизиты:
    br
    b.red LV52HABA0551038577436, Ludmila Ivanova (personas kods 300967-10223).
    br
    br

    h4 Дополнительная информация:
    br
    = link_to 'http://grani.lv', 'http://www.grani.lv/daugavpils/45218-mama-u-menya-net-nogi.html', target: '_blank'
    br
    = link_to 'http://news2night.com', 'http://news2night.com/en/news/postradavshaja-v-avarii-devushka-vertoletom-dostavlena-v-rigu', target: '_blank'
    br
    = link_to 'http://www.tvnet.lv', 'http://rus.tvnet.lv/novosti/kriminal_i_chp/261490-tragichnoje_dtp_v_daugavpilsje_djevushka_ostalas_bjez_nogi?utm_source=www.tvnet.lv&utm_medium=self_ads&utm_campaign=Selfads_in_www.tvnet', target: '_blank'
    br
    = link_to 'http://www.nasha.lv', 'http://www.nasha.lv/rus/novosti/news/incident/150166.html', target: '_blank'

    br
    br
    iframe.video width="640" height="480" src="//www.youtube.com/embed/WnLxNy4k7Qs" frameborder="0" allowfullscreen 



    h3
      |  Мы не в силах изменить произошедшее, но мы можем помочь Лине вернуться к полноценной жизни!




/ 20 июня в результате автоаварии в районе магазина «Депо» пострадала ученица нашей школы Лина Якимович. Лина доставала из багажника сумку, когда в припаркованный автомобиль сзади врезалась другая машина. В результате Лина оказалась зажатой между двумя автомобилями и получила серьезные травмы – открытые переломы ног, повреждения кровеносных сосудов. 21 июня на вертолете Лину доставили в Ригу, но, к сожалению, ногу спасти не удалось, ее пришлось ампутировать.

/ Лина – сильный духом человек, спортсменка, которая привыкла бороться с трудностями, но сейчас ей придется пережить очень сложный период адаптации к новой жизни и потребуется наша помощь и поддержка. Для лечения и реабилитации необходимы средства.

/   На имя Лининой мамы в Swedbank был открыт счет, его реквизиты:

/   LV52HABA0551038577436, Ludmila Ivanova (personas kods 300967-10223).

/ Мы не в силах изменить произошедшее, но мы можем помочь Лине вернуться к полноценной жизни!

app/views/home/index.html.slim
.container
  .row.main-page
    .lang 
      = link_to 'lv', home_set_lv_path
      =<> '/'
      = link_to 'рус', home_set_rus_path

    .col-md-12
      = image_tag 'lina1.jpg', class: 'center-margin main-img', id: 'gallery_img'
      br
      div.social
        = render 'shared/social_buttons'
      br

      ul.album
        li
          = link_to '#' do 
            = image_tag 'lina2.jpg'
        li
          = link_to '#' do
            = image_tag 'lina4.jpg'
        li
          = link_to '#' do
            = image_tag 'lina5.jpg'
        li
          = link_to '#' do
            = image_tag 'lina6.jpg'
        li
          = link_to '#' do
            = image_tag 'lina1.jpg'
        li
          = link_to '#' do
            = image_tag 'lina7.jpg'
        li
          = link_to '#' do
            = image_tag 'lina8.jpg'
        li
          = link_to '#' do
            = image_tag 'lina9.jpg'
        li
          = link_to '#' do
            = image_tag 'lina10.jpg'
        li
          = link_to '#' do
            = image_tag 'lina11.jpg'

    br
    = render "home/#{@language}"
        


= content_for :javascript do
  coffee:
    $ ->
      $('.album > li > a').hover (
        -> $('#gallery_img').attr( 'src', @.children[0].src)  
      )

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Palīdzēsim Līnai kopā!</title>
  
  <meta name="description" content="Skolēni, vecāki, draugi, visi, kas neesat vienaldzīgi!"> 
  <meta http-equiv="content-type" content="text/html;charset=UTF-8">

  <meta property="og:title" content="Palidzēsim Līnai kopā!" />
  <meta property="og:description" content="Skolēni, vecāki, draugi, visi, kas neesat vienaldzīgi!" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="http://lina.wimb.in" />
  <meta property="og:image" content="<%= image_url('lina1.jpg') %>" />


  <link rel="shortcut icon" type="image/png" href="<%= image_url('favicon.png') %>"/>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
  <%= render 'shared/ga' if Rails.env.production? %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :javascript %>  
</html>

app/views/shared/_ga.html.slim
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52369962-1', 'auto');
  ga('send', 'pageview');

app/views/shared/_social_buttons.html.erb
<div class="fb-share-button" data-href="http://lina.wimb.in" data-type="button_count"></div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&appId=420885448055834&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</br>
<a href="https://twitter.com/intent/tweet?button_hashtag=help_to_lina&text=http%3A%2F%2Flina.wimb.in" class="twitter-hashtag-button" data-lang="en-gb">Tweet #help_to_lina</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>